### ISSUE TITLE
missing some files

### ISSUE THREAD

**Issue by SeekPoint** [LiyuanLucasLiu/ReHession#1] opened 2017-10-31 06:05 UTC
bash labelGeneration.sh 
Traceback (most recent call last):
  File "LabelGeneration/post_process_chunked_corpus.py", line 20, in <module>
    with open(infile, 'r') as f:
IOError: [Errno 2] No such file or directory: './Data/source/KBP/chunked.corpus'
0
Traceback (most recent call last):
  File "LabelGeneration/MergeLFS.py", line 27, in <module>
    cur_max_idx = max(map(lambda t: max(map(lambda x: x[3], t['relationMentions'])), lines))
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "LabelGeneration/cal_Mention_Distance.py", line 21, in <module>
    with open(infile, 'r') as f:
IOError: [Errno 2] No such file or directory: './Data/source/KBP/ntrain.json'

**Comment by LiyuanLucasLiu** [comment] 2017-10-31 08:46
thanks for reporting, this problem is caused by the default parameters of scripts. 
Fixed in the newest master branch.

**Closed as completed by LiyuanLucasLiu** 2017-10-31 08:46 UTC
